# Generated by Django 2.2.19 on 2021-04-18 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='default_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
